#!/bin/bash

while read -r line; do code --install-extension "$line"; done < ~/bash-scripts/assets/extensions.txt
cp -f ~/.config/Code/User/settings.json ~/bash-scripts/assets/settings.json # replace [original file] [new file]
printf "\n" 
printf "Custom VScode config complete!"
